name: release22
on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: Rakshithb1/helm-gh-pages@main
        with:
          token: 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